services:
    - type: web
      name: react-frontend
      env: static
      buildCommand: npm install && npm run build
      staticPublishPath: dist
      envVars:
          - key: VITE_API_URL
            value: https://proxy-server-t6hm.onrender.com/api
